import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'

const opeOpen_Sans = Open_Sans({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
	title: 'Movie Library 2.0',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={opeOpen_Sans.className}>{children}</body>
		</html>
	)
}
